services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    networks:
      - media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    volumes:
      - /home/damian/docker/bazarr/config:/config
      - /srv/toshiba/data:/data
    ports:
      - "6767:6767"

networks:
  media:
    external: true
